language: java
sudo: false
notifications:
  email:
    on_success: never
    on_failure: always
git:
  submodules: false
jdk:
  - oraclejdk8
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - ant install-ivy
install:
  - ant install
  - sed -i 's/${ant\.java\.version}/1.8/g' wpilib/ant/build.xml
  - sed -i 's/${ant\.java\.version}/1.8/g' build.xml
  - sed -i 's/${ant\.java\.version}/1.8/g' default.xml
  - sed -i 's/${ant\.java\.version}/1.8/g' ./*.xml
  - sed -i 's/${ant\.java\.version}/1.8/g' FRamework/*.xml
  - sed -i 's/compiler="javac1.8"//g' wpilib/ant/build.xml
  - sed -i 's/compiler="javac1.8"//g' *.xml
  - sed -i 's/compiler="javac1.8"//g' FRamework/*.xml
  - ant checkstyle
  - ant compile
